trigger:
  branches:
    include:
      - docker

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'flaskcalc'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
    python -m unittest discover tests
  displayName: 'Install deps & run tests'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    containerRegistry: 'acr-marek'  # <<< ZMIEŃ na nazwę Twojego service connection do ACR
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)

- task: Docker@2
  displayName: 'Push Docker image to ACR'
  inputs:
    containerRegistry: 'acr-marek'  # <<< ZMIEŃ na tę samą nazwę
    repository: '$(imageName)'
    command: 'push'
    tags: |
      $(Build.BuildId)
