trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  pythonVersion: '3.11'
  deploy: false

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'

- script: |
    python -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    source venv/bin/activate
    python -m unittest discover tests
  displayName: 'Run tests'

- task: AzureWebApp@1
  condition: eq(variables['deploy'}, 'true')
  inputs:
    azureSubscription: 'azure-sp-connection'  # <- tu daj nazwę swojego service connection
    appName: 'azure-flask-app-calculator'     # <- nazwa Twojego App Service
    package: '.'                              # <- bieżący katalog (czyli cały kod źródłowy)
